name: Netflix Movie Catalog Service Deployment

on:
  push:
    branches:
      - main

env:
  EC2_PUBLIC_IP: 3.64.252.72 
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }} 
  DOCKERHUB_USERNAME: doramar97

jobs:
  Deploy:
    name: Deploy in EC2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the app code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Build and push Docker image to Dockerhub
        run: | 
          docker build -t ${DOCKERHUB_USERNAME}/netflix-movie-catalog .
          docker push ${DOCKERHUB_USERNAME}/netflix-movie-catalog
          
      - name: SSH to EC2 instance
        run: | 
          echo "$SSH_PRIVATE_KEY" > dor.pem
          chmod 400 dor.pem
          scp -o StrictHostKeyChecking=no -i dor.pem deploy.sh ubuntu@$EC2_PUBLIC_IP:~/app
          ssh -i dor.pem ubuntu@$EC2_PUBLIC_IP "bash ~/app/deploy.sh"